version: '3'

services:
  nonogram-api:
    build: .
    ports:
      - "5555:8080"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
